# Travis-CI configuration

sudo: true
services:
    - docker

language: cpp

# :TODO: @brad Add osx build (need homebrew packages)..
matrix:
  include:
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-debian-stable-gcc8
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-debian-testing-gcc9


addons:
  apt:
    packages:
      - docker-ce


# Limit number of commits in cloning (but keep enough so that 'git describe' works)
git:
  depth: 100


install:
  - docker build -t spatialdata-testenv --build-arg BASE_IMAGE=$BASE_IMAGE --target src -f docker/spatialdata-testenv .


script: 
  - docker run spatialdata-testenv /bin/bash -c "make -j$(nproc) install && make -j$(nproc) check VERBOSE=1"
