# Travis-CI configuration

sudo: true
services:
    - docker

language: cpp

# :TODO: @brad Add osx build (need homebrew packages)..
matrix:
  include:
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-debian-stable-gcc8 TEST_COVERAGE=yes PYTHON_COVERAGE=python2-coverage
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-debian-testing-gcc9 TEST_COVERAGE=yes PYTHON_COVERAGE=python2-coverage
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-ubuntu-18.04 TEST_COVERAGE=yes PYTHON_COVERAGE=python2-coverage
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-ubuntu-19.10 TEST_COVERAGE=yes PYTHON_COVERAGE=python2-coverage
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-ubuntu-20.04 TEST_COVERAGE=yes PYTHON_COVERAGE=python2-coverage
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-fedora-30 TEST_COVERAGE=yes PYTHON_COVERAGE=coverage2
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-fedora-31 TEST_COVERAGE=yes PYTHON_COVERAGE=coverage2
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-fedora-32
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-centos-6
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-centos-7
    - os: linux
      env: BASE_IMAGE=geodynamics/pylith-testenv-centos-8

# Permissions problem with BUILD_DIR for nemesis.
#    - os: linux
#      env: BASE_IMAGE=geodynamics/pylith-testenv-fedora-33

#    - os: linux
#      env: BASE_IMAGE=geodynamics/pylith-testenv-debian-testing-clang8
#    - os: linux
#      env: BASE_IMAGE=geodynamics/pylith-testenv-debian-testing-clang9


addons:
  apt:
    packages:
      - docker-ce


# Limit number of commits in cloning (but keep enough so that 'git describe' works)
git:
  depth: 100


install:
  - docker build -t spatialdata-testenv --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg TEST_COVERAGE=$TEST_COVERAGE --build-arg PYTHON_COVERAGE=$PYTHON_COVERAGE --target src -f docker/spatialdata-testenv .


script: 
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env spatialdata-testenv ../../src/spatialdata/ci-config/run_test_coverage.sh
