# Travis-CI configuration

sudo: false

language: cpp

matrix:
  include:
    - os: linux
      env: LD_LIBRARY_PATH="$HOME/dist/deps/lib:$HOME/dist/target/lib:$LD_LIBRARY_PATH" CREATE_CACHE=1

# Limit number of commits in cloning
git:
  depth: 1

# Build dependencies (will use cache if CREATE_CACHE is undefined)
install:
  - if [ $CREATE_CACHE ]; then travis/dependencies.sh build; fi
  - ls -lR dist/deps

script: 
  - git fetch --unshallow
  - autoreconf --install --verbose --force && ./configure --enable-swig --enable-testing --enable-pythia --prefix="$HOME/dist/target" CPPFLAGS="-I$HOME/dist/deps/include -I$HOME/dist/target/include" LDFLAGS="-L$HOME/dist/deps/lib -L$HOME/dist/target/lib" && make -j2 && make install && make -j2 check

env:
  global:
    - PATH="$HOME/dist/deps/bin:$HOME/dist/target/bin:$PATH"
    - PYTHONPATH="$HOME/dist/deps/lib/python2.7/site-packages:$HOME/dist/target/lib/python2.7/site-packages:$PYTHONPATH"

cache:
  timeout: 300
  directories:
    - $HOME/dist/deps
