# Travis-CI configuration

language: cpp

matrix:
  include:
    - os: linux
      env: TARBALL=pylith_deps-travis-ubuntu-12.04-amd64.tgz LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/dist/lib:$LD_LIBRARY_PATH

# Limit number of commits in cloning
git:
  depth: 10

# Install dependencies cached on CIG server
install:
  - mkdir -p dist && pushd dist && curl -O http://geoweb.cse.ucdavis.edu/~buildbot/deps/$TARBALL && tar -zxvf $TARBALL && popd

script: 
  - git fetch --unshallow
  - mkdir -p build && pushd build && autoreconf --install --verbose --force $TRAVIS_BUILD_DIR && $TRAVIS_BUILD_DIR/configure --enable-swig --enable-testing --enable-pythia --prefix=$TRAVIS_BUILD_DIR/dist CPPFLAGS=-I$TRAVIS_BUILD_DIR/dist/include LDFLAGS=-L$TRAVIS_BUILD_DIR/dist/lib && make && make install && make check && popd

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/dist/bin:$PATH
    - PYTHONPATH=$TRAVIS_BUILD_DIR/dist/lib/python2.7/site-packages:$PYTHONPATH
    - SWIG_LIB=$TRAVIS_BUILD_DIR/dist/share/swig/2.0.6
    - PROJ_LIB=$TRAVIS_BUILD_DIR/dist/share/proj
