# Travis-CI configuration

language: cpp

matrix:
  include:
    - os: linux
      env: LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/dist/deps/lib:$TRAVIS_BUILD_DIR/dist/target/lib:$LD_LIBRARY_PATH"

# Limit number of commits in cloning
git:
  depth: 1

# Build dependencies (will use cache if CREATE_CACHE is undefined)
install:
  - if [ $CREATE_CACHE ]; then travis/dependencies.sh build; fi
  - ls -lR dist/deps

script: 
  - git fetch --unshallow
  - autoreconf --install --verbose --force && $TRAVIS_BUILD_DIR/configure --enable-swig --enable-testing --enable-pythia --prefix="$TRAVIS_BUILD_DIR/dist/target" CPPFLAGS="-I$TRAVIS_BUILD_DIR/dist/deps/include -I$TRAVIS_BUILD_DIR/dist/target/include" LDFLAGS="-L$TRAVIS_BUILD_DIR/dist/deps/lib -L$TRAVIS_BUILD_DIR/dist/target/lib" && make -j2 && make install && make -j2 check

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/dist/deps/bin:$TRAVIS_BUILD_DIR/dist/target/bin:$PATH"
    - PYTHONPATH="$TRAVIS_BUILD_DIR/dist/deps/lib/python2.7/site-packages:$TRAVIS_BUILD_DIR/dist/target/lib/python2.7/site-packages:$PYTHONPATH"

cache:
  directories:
    - dist/deps
