// =================================================================================================
// This code is part of SpatialData, developed through the Computational Infrastructure
// for Geodynamics (https://github.com/geodynamics/spatialdata).
//
// Copyright (c) 2010-2025, University of California, Davis and the SpatialData Development Team.
// All rights reserved.
//
// See https://mit-license.org/ and LICENSE.md and for license information.
// =================================================================================================

// See UniformVelModel.hh for a description of each C++ function and its arguments.

#include <portinfo> // machine specific info generated by configure

#include "UniformVelModel.hh" // Implementation of class methods

#include "spatialdata/spatialdb/Utilities.hh" // USES search()
#include "spatialdata/spatialdb/Exception.hh" // USES ValueNotFound
#include "spatialdata/geocoords/CSGeo.hh" // USES CSGeoProj
#include "spatialdata/geocoords/Converter.hh" // USES Converter

#include <strings.h> // USES strcasecmp()
#include <cassert> // USES assert()
#include <sstream> // USES std::ostringstream
#include <stdexcept> // USES std::runtime_error, std::logic_error

namespace contrib {
    namespace spatialdb {
        class _UniformVelModel {
public:

            // Indices of values in database (used in queryVals to indicate
            // which values to return in a query).
            enum QueryValsEnum {
                QUERY_VP=0, // vp
                QUERY_VS=1, // vs
                QUERY_DENSITY=2, // density
            }; // ValsEnum

        };
    }
}

// ----------------------------------------------------------------------
// Constructor
contrib::spatialdb::UniformVelModel::UniformVelModel(const char* description) :
    spatialdata::spatialdb::SpatialDB(description),
    _vp(0),
    _vs(0),
    _density(0),
    _cs(new spatialdata::geocoords::CSGeo),
    _names({"vp", "vs", "density"}) {
    assert(_cs);
    _cs->setSpaceDim(3);
    _cs->setString("EPSG:4267");

}


// ----------------------------------------------------------------------
// Destructor
contrib::spatialdb::UniformVelModel::~UniformVelModel(void) {}


// ----------------------------------------------------------------------
// Open the database and prepare for querying.
void
contrib::spatialdb::UniformVelModel::open(void) {
    // Make sure the physical properties have been set.
    if (0 == _vs) {
        std::ostringstream msg;
        msg << "S wave speed has not been set for spatial database "
            << getDescription() << ".";
        throw std::runtime_error(msg.str());
    } // if
    if (0 == _vp) {
        std::ostringstream msg;
        msg << "P wave speed has not been set for spatial database "
            << getDescription() << ".";
        throw std::runtime_error(msg.str());
    } // if
    if (0 == _density) {
        std::ostringstream msg;
        msg << "Density has not been set for spatial database "
            << getDescription() << ".";
        throw std::runtime_error(msg.str());
    } // if

    // Default query values
    this->setQueryValues({"vp", "vs", "density"});
} // open


// ----------------------------------------------------------------------
// Close the database.
void
contrib::spatialdb::UniformVelModel::close(void) {
    _queryIndices.clear();_queryIndices.shrink_to_fit();
} // close


// ----------------------------------------------------------------------
// Get names of values in spatial database.
const std::vector<std::string>&
contrib::spatialdb::UniformVelModel::getNamesDBValues(void) const {
    return _names;
} // getNamesDBValues


// ----------------------------------------------------------------------
// Set values to be returned by queries.
void
contrib::spatialdb::UniformVelModel::setQueryValues(const std::vector<std::string>& names) {
    if (0 == names.size()) {
        std::ostringstream msg;
        msg << "Number of values for query in spatial database " << getDescription()
            << " must be positive.\n";
        throw std::invalid_argument(msg.str());
    } // if

    const size_t querySize = names.size();
    _queryIndices.clear();
    _queryIndices.reserve(querySize);
    for (size_t iQuery = 0; iQuery < querySize; ++iQuery) {
        try {
            const size_t iName = spatialdata::spatialdb::Utilities::search(_names, names[iQuery].c_str(), getDescription());
            _queryIndices.emplace_back(iName);
        } catch (const spatialdata::spatialdb::ValueNotFound& err) {
            throw;
        } catch (...) {
            throw std::logic_error("Unknown error in settting query values.");
        } // try/catch
    } // for
} // setQueryVals


// ----------------------------------------------------------------------
// Query the database.
int
contrib::spatialdb::UniformVelModel::query(double* values,
                                           const size_t numValues,
                                           const double* coordinates,
                                           const spatialdata::geocoords::CoordSys* csCoordinates) {
    assert(!numValues || values);
    assert(coordinates);
    assert(csCoordinates);

    const size_t spaceDim = csCoordinates->getSpaceDim();
    const size_t querySize = _queryIndices.size();
    if (0 == querySize) {
        std::ostringstream msg;
        msg << "Values to be returned by spatial database " << getDescription() << "\n"
            << "have not been set. Please call setQueryValues() before query().\n";
        throw std::logic_error(msg.str());
    } // if
    else if (numValues != querySize) {
        std::ostringstream msg;
        msg << "Number of values to be returned by spatial database "
            << getDescription() << "\n"
            << "(" << querySize << ") does not match size of array provided ("
            << numValues << ").\n";
        throw std::invalid_argument(msg.str());
    } else if (spaceDim != _cs->getSpaceDim()) {
        std::ostringstream msg;
        msg << "Spatial dimension (" << spaceDim
            << ") does not match spatial dimension of spatial database (" << _cs->getSpaceDim() << ").";
        throw std::invalid_argument(msg.str());
    } // if

    // Convert coordinates to local coordinate system. Not useful for
    // this trivial seismic velocity model but will be necessary in most
    // cases.
    _xyz[0] = 0.0;
    _xyz[1] = 0.0;
    _xyz[2] = 0.0;
    for (size_t iDim = 0; iDim < spaceDim; ++iDim) {
        _xyz[iDim] = coordinates[iDim];
    }
    spatialdata::geocoords::Converter().convert(_xyz, 1, spaceDim, _cs.get(), csCoordinates);

    // Perform query operation
    int queryFlag = 0;
    for (int iQuery = 0; iQuery < querySize; ++iQuery) {
        switch (_queryIndices[iQuery]) {
        case _UniformVelModel::QUERY_VP:
            values[iQuery] = _vp;
            break;
        case _UniformVelModel::QUERY_VS:
            values[iQuery] = _vs;
            break;
        case _UniformVelModel::QUERY_DENSITY:
            values[iQuery] = _density;
            break;
        default:
            throw std::logic_error("Unknown query value.");
        } // switch
    } // for

    return queryFlag;
} // query


// ----------------------------------------------------------------------
// Set the P wave speed.
void
contrib::spatialdb::UniformVelModel::setVp(const double value) {
    if (value <= 0.0) {
        std::ostringstream msg;
        msg << "P wave speed must be positive for uniform velocity model "
            << "database " << getDescription() << ".\n";
        throw std::runtime_error(msg.str());
    } // if

    _vp = value;
} // setVp


// ----------------------------------------------------------------------
// Set the S wave speed.
void
contrib::spatialdb::UniformVelModel::setVs(const double value) {
    if (value < 0.0) {
        std::ostringstream msg;
        msg << "S wave speed must be nonnegative for uniform velocity model "
            << "database " << getDescription() << ".\n";
        throw std::out_of_range(msg.str());
    } // if

    _vs = value;
} // setVs


// ----------------------------------------------------------------------
// Set the density.
void
contrib::spatialdb::UniformVelModel::setDensity(const double value) {
    if (value <= 0.0) {
        std::ostringstream msg;
        msg << "Density must be positive for uniform velocity model database "
            << getDescription() << ".\n";
        throw std::out_of_range(msg.str());
    } // if

    _density = value;
} // setDensity


// End of file
